### ISSUE TITLE
How do I install this to my Apple Watch

### ISSUE THREAD

**Issue by ATuxford** [hbiede/Lazy-Clock#2]
I can’t seem to see how to get Lazy Clock as the watch face on my Apple Watch. Can you please assist?

Thanks

**Comment by hbiede** [comment]
Hi, thanks for reaching out to me. Unfortunately, due to the limitations of watchOS set by Apple, you cannot have 3rd party apps (such as Lazy Clock) as you main watch face. However, you can open the app and the watch should open it again when you look at the watch. I try my best with the possibilities I’m given by Apple.
